### ISSUE TITLE
register_affine bug

### ISSUE THREAD

**Issue by vikramc1** [neurodata/ndreg#16]
- origin of input image (not atlas) is changed, resulting in inaccurate registration

**Comment by gungne** [comment]
Just figure it out: 
sitk always assume the first input is the fixed image, in your affine and rigid transformation, you accidentally put them in reverse order. 

>     final_transform = registration_method.Execute(sitk.Cast(img, sitk.sitkFloat32),
                                                  sitk.Cast(atlas, sitk.sitkFloat32))

Copied and run custom fixed function of affine registration, seems working fine for me. 
Could you please verify this issue and update the code? Many thanks.

Reference:
https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1ImageRegistrationMethod.html
